routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::match(['get', 'post'], '/botman', 'BotManController@handle');

Route::match(['get'], '/', 'PagesController@index');

// CRUD ROUTES
Route::resource('category', 'CategoryController');
Route::resource('breakfast', 'BreakfastController');
Route::resource('lunch', 'LunchController');
Route::resource('lunchdate', 'LunchdateController');
Route::get('week', 'LunchdateController@week');
Route::post('week', 'LunchdateController@storeMany');
Route::resource('messagetype', 'MessagetypeController');
Route::resource('message', 'MessageController');

// AJAX ROUTES
Route::post('/addbfast', 'AjaxController@breakfaststore');
Route::post('/addlunch', 'AjaxController@lunchstore');

// Lunchbot slack webhook
// Route::get('today', 'BotManController@today');
Route::post('/listening', 'SlackController@listening');

app/Message.php
<?php namespace App;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

/**
* Category Model (Categories)
* NAME: Name of category, is it lunch (true false)
*/

class Message extends Model
{

	use SoftDeletes;
	protected $dates = ['deleted_at'];
	protected $table = 'messages';

	protected $fillable = ['id', 'text', 'message_type_id'];

	public function message_type() {

		return $this->belongsTo('App\Messagetype');

	}

}

app/Messagetype.php
<?php namespace App;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

/**
* Category Model (Categories)
* NAME: Name of category, is it lunch (true false)
*/

class Messagetype extends Model
{

	use SoftDeletes;
	protected $dates = ['deleted_at'];
	protected $table = 'message_types';

	protected $fillable = ['id', 'name'];

	public function messages() {

		return $this->hasMany('App\Message');

	}

}

app/Http/Controllers/MessageController.php
<?php
namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\Message;
use App\Messagetype;

class MessageController extends Controller
{

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
        $messages = Message::orderBy('id','DESC')
            ->with('message_type')
            ->paginate(50);
        return view('message.index',compact('messages'))
            ->with('i', ($request->input('page', 1) - 1) * 50);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $messagetypes = Messagetype::pluck('name','id');
        return view('message.create', compact('messagetypes'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {

        Message::create([
            'text' => $request->input('text'),
            'message_type_id' => $request->input('message_type_id')
        ]);

        return redirect()->route('message.index')
            ->with('success','Message created successfully');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $message = Message::with('message_type')->find($id);
        return view('message.show',compact('message'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $message = Message::find($id);
        $messagetypes = Messagetype::pluck('name','id');
        return view('message.edit',compact('message','messagetypes'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {

        message::find($id)->update([
            'text' => $request->input('text'),
            'message_type_id' => $request->input('message_type_id')
        ]);
        return redirect()->route('message.index')
            ->with('success','message updated successfully');

    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        Message::find($id)->delete();
        return redirect()->route('message.index')
            ->with('success','message deleted successfully');
    }
}

resources/views/message/create.blade.php
@extends('layouts.default')

@section('content')

    <div class="row">
        <div class="col-lg-12 margin-tb">
            <div class="pull-left">
                <h2>Create New Message</h2>
            </div>
            <div class="pull-right">
                <a class="btn btn-primary" href="{{ route('message.index') }}"> Back</a>
            </div>
        </div>
    </div>

    @if (count($errors) > 0)
        <div class="alert alert-danger">
            <strong>Whoops!</strong> There were some problems with your input.<br><br>
            <ul>
                @foreach ($errors->all() as $error)
                    <li>{{ $error }}</li>
                @endforeach
            </ul>
        </div>
    @endif

    {!! Form::open(array('route' => 'message.store','method'=>'POST')) !!}
    <div class="row">

        <div class="col-xs-12 col-sm-12 col-md-12">
            <div class="form-group">
                <strong>Text:</strong>
                {!! Form::text('text', null, array('placeholder' => 'Lunch is awesome','class' => 'form-control')) !!}
            </div>
        </div>

        <div class="col-xs-12 col-sm-12 col-md-12">
            <div class="form-group">
                <strong>Type:</strong>
                {!! Form::select('message_type_id', $messagetypes , null, array('class' => 'form-control')) !!}
            </div>
        </div>

        <div class="col-xs-12 col-sm-12 col-md-12 text-center">
                <button type="submit" class="btn btn-primary">Submit</button>
        </div>

    </div>
    {!! Form::close() !!}

@endsection

resources/views/message/edit.blade.php
@extends('layouts.default')
 
@section('content')

    <div class="row">
        <div class="col-lg-12 margin-tb">
            <div class="pull-left">
                <h2>Edit Lunch</h2>
            </div>
            <div class="pull-right">
                <a class="btn btn-primary" href="{{ route('message.index') }}"> Back</a>
            </div>
        </div>
    </div>

    @if (count($errors) > 0)
        <div class="alert alert-danger">
            <strong>Whoops!</strong> There were some problems with your input.<br><br>
            <ul>
                @foreach ($errors->all() as $error)
                    <li>{{ $error }}</li>
                @endforeach
            </ul>
        </div>
    @endif

    {!! Form::model($message, ['method' => 'PATCH','route' => ['message.update', $message->id]]) !!}
    <div class="row">

        <div class="col-xs-12 col-sm-12 col-md-12">
            <div class="form-group">
                <strong>Text:</strong>
                {!! Form::text('text', $message->text, array('placeholder' => 'Name','class' => 'form-control')) !!}
            </div>
        </div>
        
        <div class="col-xs-12 col-sm-12 col-md-12">
            <div class="form-group">
                <strong>Type:</strong>
                {!! Form::select('message_type_id', $messagetypes , $message->message_type_id, array('class' => 'form-control')) !!}
            </div>
        </div>

        <div class="col-xs-12 col-sm-12 col-md-12 text-center">
                <button type="submit" class="btn btn-primary">Submit</button>
        </div>

    </div>
    {!! Form::close() !!}

@endsection

resources/views/message/index.blade.php
@extends('layouts.default')
 
@section('content')

    <div class="row">
        <div class="col-lg-12 margin-tb">
            <div class="pull-left">
                <h2>Messages</h2>
            </div>
            <div class="pull-right">
                <a class="btn btn-success" href="{{ route('message.create') }}"> Create New Message</a>
            </div>
        </div>
    </div>

    @if ($message = Session::get('success'))
        <div class="alert alert-success">
            <p>{{ $message }}</p>
        </div>
    @endif

    <table class="table table-bordered">
        <tr>
            <th>text</th>
            <th>Type</th>
            <th width="280px">Action</th>
        </tr>
    @foreach ($messages as $key => $item)
    <tr>
        <td>{{ $item->text }}</td>
        <td>{{ $item->message_type->name }}
        <td>
            <a class="btn btn-info" href="{{ route('message.show',$item->id) }}">Show</a>
            <a class="btn btn-primary" href="{{ route('message.edit',$item->id) }}">Edit</a>
            {!! Form::open(['method' => 'DELETE','route' => ['message.destroy', $item->id],'style'=>'display:inline']) !!}
            {!! Form::submit('Delete', ['class' => 'btn btn-danger']) !!}
            {!! Form::close() !!}
        </td>
    </tr>
    @endforeach
    </table>

    {!! $messages->render() !!}

@endsection

resources/views/message/show.blade.php
@extends('layouts.default')
 
@section('content')

    <div class="row">
        <div class="col-lg-12 margin-tb">
            <div class="pull-left">
                <h2>Show Lunch</h2>
            </div>
            <div class="pull-right">
                <a class="btn btn-primary" href="{{ route('lunch.index') }}"> Back</a>
            </div>
        </div>
    </div>

    <div class="row">

        <div class="col-xs-12 col-sm-12 col-md-12">
            <div class="form-group">
                <strong>Name:</strong>
                {{ $lunch->name }}
            </div>
        </div>

        <div class="col-xs-12 col-sm-12 col-md-12">
            <div class="form-group">
                <strong>Category:</strong>
                {{ $lunch->category->name }}
            </div>
        </div>

        <div class="col-xs-12 col-sm-12 col-md-12">
            <div class="form-group">
                <strong>Is It Healthy?</strong>
                {{ $lunch->healthy }}
            </div>
        </div>

    </div>

@endsection